name: Music API CI

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:12.9

        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Spotify.settings

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9



      - name: Install requirements # install application requirements
        run: pip install -r requirements.txt #install requirements
      - name: Run Test # running tests
        run: python manage.py test












